name: utf2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pytest
  - pyyaml
  - requests
  - pre-commit
  - jupyterlab
  - pip
  - pip:
      - jq
