name: utf2
channels:
  - conda-forge
  - defaults
dependencies:
  # --- Core Python ---
  - python=3.10
  - pip
  - ipython
  - jupyterlab
  - notebook

  # --- Scientific Stack ---
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - sympy

  # --- Reproducibility & Validation ---
  - pytest
  - pytest-cov
  - pre-commit
  - flake8
  - black
  - isort

  # --- Versioning & Metadata Tools ---
  - gitpython
  - pyyaml
  - jsonschema

  # --- Visualization & Export ---
  - graphviz
  - python-graphviz
  - pillow

  # --- Documentation / Reports ---
  - sphinx
  - sphinx_rtd_theme
  - pandoc

  # --- Zenodo / arXiv Integration ---
  - requests
  - tqdm

  # --- Environment Management ---
  - conda-build
  - conda-lock

  # --- Optional GPU or HPC (comment out if not used) ---
  # - cudatoolkit=11.8
  # - cupy

  # --- pip Extras (for utf modules) ---
  - pip:
      - pre-commit-hooks
      - gitpython
      - jupyterlab-vim
      - rich
      - colorama
      - tabulate
      - markdownify
      - zenodo-api-client
      - arxiv

# Environment variables for reproducibility
variables:
  UTF_DEBUG: "0"
  UTF_DATA_DIR: "./data"
  MPLBACKEND: "Agg"  # headless CI-safe plotting
